"""Link trips to vehicles

Revision ID: 21e1939e2fe8
Revises: 27e1a7ca3109
Create Date: 2026-09-05 11:00:30.586431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e1939e2fe8'
down_revision: Union[str, Sequence[str], None] = '27e1a7ca3109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'trips', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_column('trips', 'vehicle_id')
    # ### end Alembic commands ###
