"""Add trip fuel model

Revision ID: 27e1a7ca3109
Revises: 31aad5d31d2e
Create Date: 2026-09-05 10:28:59.119431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e1a7ca3109'
down_revision: Union[str, Sequence[str], None] = '31aad5d31d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_fuels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('starting_fuel', sa.Float(), nullable=False),
    sa.Column('current_fuel', sa.Float(), nullable=False),
    sa.Column('fuel_used', sa.Float(), nullable=False),
    sa.Column('fuel_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_fuels_trip_id'), 'trip_fuels', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_fuels_trip_id'), table_name='trip_fuels')
    op.drop_table('trip_fuels')
    # ### end Alembic commands ###
