"""Add EV fields to vehicles

Revision ID: 31aad5d31d2e
Revises: 0591b20cce56
Create Date: 2026-09-05 10:05:58.808758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31aad5d31d2e'
down_revision: Union[str, Sequence[str], None] = '0591b20cce56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('battery_capacity', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('energy_consumption', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'energy_consumption')
    op.drop_column('vehicles', 'battery_capacity')
    # ### end Alembic commands ###
