"""add coordinates to trip destinations

Revision ID: b34915e21131
Revises: 93e429b764a6
Create Date: 2026-09-03 18:02:52.504075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34915e21131'
down_revision: Union[str, Sequence[str], None] = '93e429b764a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_destinations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('trip_destinations', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_destinations', 'longitude')
    op.drop_column('trip_destinations', 'latitude')
    # ### end Alembic commands ###
