"""add trip budget

Revision ID: ba2449df3282
Revises: cc71c8851099
Create Date: 2026-09-08 19:04:25.442754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2449df3282'
down_revision: Union[str, Sequence[str], None] = 'cc71c8851099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('estimated_fuel_cost', sa.Float(), nullable=False),
    sa.Column('estimated_ev_charging_cost', sa.Float(), nullable=False),
    sa.Column('estimated_toll_cost', sa.Float(), nullable=False),
    sa.Column('estimated_food_cost', sa.Float(), nullable=False),
    sa.Column('estimated_parking_cost', sa.Float(), nullable=False),
    sa.Column('estimated_other_cost', sa.Float(), nullable=False),
    sa.Column('actual_fuel_cost', sa.Float(), nullable=False),
    sa.Column('actual_ev_charging_cost', sa.Float(), nullable=False),
    sa.Column('actual_toll_cost', sa.Float(), nullable=False),
    sa.Column('actual_food_cost', sa.Float(), nullable=False),
    sa.Column('actual_parking_cost', sa.Float(), nullable=False),
    sa.Column('actual_other_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_budgets_trip_id'), 'trip_budgets', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_budgets_trip_id'), table_name='trip_budgets')
    op.drop_table('trip_budgets')
    # ### end Alembic commands ###
