"""Add trip EV state

Revision ID: cc71c8851099
Revises: fe4107fc2553
Create Date: 2026-09-08 08:47:52.672269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc71c8851099'
down_revision: Union[str, Sequence[str], None] = 'fe4107fc2553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_evs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('starting_battery_percentage', sa.Float(), nullable=False),
    sa.Column('current_battery_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_evs_trip_id'), 'trip_evs', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_evs_trip_id'), table_name='trip_evs')
    op.drop_table('trip_evs')
    # ### end Alembic commands ###
